version: "3.9"
services:
  web:
    build: ./web
    
    ports:
      - "8000:3000"

  server:
    build: ./server
    environment:
      PORT: 8003
      PGUSER: "postgres"
      PGHOST: "db"
      PGPASSWORD: "example" 
      PGDATABASE: "dogs" 
      PGPORT: "5432" 
    expose:
      - 8003
    ports:
      - "8003:8003"

  db:
    build: ./db
    ports:
      - "8001:5432"

  adminer:
    image: adminer
    ports:
      - "8002:8080"