name: build_push

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "image tag"
        required: true

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies server
        run: cd server && npm install server && cd ..

      - name: Install dependencies client
        run: cd web && npm install server && cd ..

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/rma-project-frontend:${{ github.event.inputs.tag }}, ghcr.io/${{ github.repository }}/rma-project-frontend:latest
